version: "3"
   
services:
  zspa:
    image: 192.168.50.7:6088/hawwestin/zspaweb:latest
    volumes:
      - static_data:/vol/web
    env_file:
      - .env
    environment:
      - DEBUG=False
    depends_on:
      proxy:
        condition: service_started

  proxy:
    image: 192.168.50.7:6088/hawwestin/zspaproxy:latest
    volumes:
      - static_data:/vol
    ports:
      - "8090:8080"


volumes:
  static_data:
